name: Python Cache Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  cache-python-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: prime-cache-fa22da5
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-fa22da5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Echo cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
